### PR TITLE
Poincare ball model

### PR DESCRIPTION
**Pull request by ferrine**
Huray, we are ready to start.

image
Image from [here](https://www.researchgate.net/publication/226215689_The_Hyperbolic_Geometric_Structure_of_the_Density_Matrix_for_Mixed_State_Qubits)

Interesting reading I've done so far:

[Hyperbolic Networks](https://arxiv.org/abs/1805.09112)
[Hyperbolic Entailment Cones for Learning Hierarchical Embeddings](https://arxiv.org/abs/1804.01882)
[Poincaré GloVe: Hyperbolic Word Embeddings](https://www.groundai.com/project/poincare-glove-hyperbolic-word-embeddings/ )

Some implementation takeouts (mostly from [here](https://arxiv.org/abs/1805.09112)):
* Project results of all operations in the ball of radius `1 − eps`, where `eps = 10^{-5}`
* Numerical errors also appear when hyperbolic vectors get closer to 0, perturb with `eps = 10^{-15}`
* Pass clipped to `[-15, 15]` input to `tanh` and clip `tanh^{-1}` to `[-1+eps, 1-eps]`

CC @leuchine!

### CODE REVIEW

**Comment by leuchine** [comment]
Thanks! @ferrine  This is very insightful!

**Comment by KhrulkovV** [comment]
Very interesting, perhaps we can add more models (Lorentz hyperboloid model which is more stable for numerical optimization) later?

**Comment by ferrine** [comment]
@KhrulkovV Hi! Happy to see you there. I'll check that paper!

**Comment by ferrine** [comment]
I've tried to write some tests for parallel transport in Poincare ball model and found it a frustrating idea. Parallel transport is very numerically unstable and sometimes gives ridiculous errors passing sometimes. Trying to see what happens, I've plotted it in matplotlib and it was visually ok and perhaps makes little sense.
image

BTW, I found a way to add figures to docs, it will be neat

**Comment by ferrine** [comment]
I'm done. There are some docs+implementation. Waiting for tests pass now

**Comment by ferrine** [comment]
Tests with adam do not work if I use torch script, as:
https://github.com/pytorch/pytorch/issues/14455

**Comment by leuchine** [comment]
Hi. @ferrine. I found that some adaptive methods like https://openreview.net/forum?id=r1eiqi09K7 maybe work better than plain Adam here. Thanks!

**Comment by leuchine** [comment]
Hi @ferrine . Thanks for taking your efforts to implement the Poincare model. Here is another paper on Lorentz model, which may be of interests to you. https://arxiv.org/pdf/1902.00913.pdf 

Also, may I ask that do you mind sharing your scripts for drawing the tests for parallel transport in Poincare ball model? I plan to use it for testing my own parallel transport implementation. Thanks!

Best Regards,
Qi

**Comment by ferrine** [comment]
Sure, I have docs with plots also. Here is the requested source code

https://github.com/ferrine/geoopt/blob/f7e842d559fc6e9de9b02bec31420ec1888df6b8/docs/plots/extended/poincare/parallel_transport.py

And docs also

https://geoopt.readthedocs.io/en/poincare/extended/poincare.html

Docs will change soon. I think they worth to be polished

--
Max

вт, 26 февр. 2019 г., 0:51 Qi Liu <notifications@github.com>:

**Comment by leuchine** [comment]
Thanks! @ferrine  This is very helpful.

**Comment by ferrine** [comment]
Could anyone of you review docs [here](https://geoopt.readthedocs.io/en/poincare/extended/poincare.html)? Maybe @leuchine or @newkozlukov if you have free time?

The checklist is the following:
* Docstring is rendered correctly
* Docstring is easy to read
* Plots are easy to read, they contain enough information to get a better intuition. (I'm fine to redo them)
* There are no typos
* There are no math typos
* Name conventions are held, the function name is not misleading and its arguments are self explained

If **Any** of these points are violated, please write a short comment in the corresponding place. I believe this is the way to create better docs.

**Comment by leuchine** [comment]
Thanks! @ferrine  I will try to read it this week.

**Comment by leuchine** [comment]
I just glanced through. The doc looks great. I will continue later.

A Typo: Exp, Log -> exp, log

BTW, the Lorentz model including exp, log and parallel transport has already been implemented here. @ferrine @KhrulkovV . https://github.com/facebookresearch/poincare-embeddings/blob/master/hype/lorentz.py 
Also, as there are mapping functions from Poincare to Lorentz and vice versa, these code might be reused. Thanks!

**Comment by KhrulkovV** [comment]
There is a small typo in docs: distance on hyperboloid is arccosh(x, y), not arccos(x, y). Will read more carefully later.

**Comment by ferrine** [comment]
@leuchine 
> A Typo: Exp, Log -> exp, log
I used a capital letter to distinguish this operation from regular `exp/log`. Is it a convention to use lowercase?

**Comment by leuchine** [comment]
@ferrine  It is not a big problem. Just a small convention in math publications I think. :) Low priority. Thanks!

**Comment by ferrine** [comment]
Any additional comments, guys? Eager to continue the PR

**Comment by ferrine** [comment]
I've observed weird behavior in `torch.jit.trace` (#57) rebased to follow master branch

**Comment by ferrine** [comment]
There are some fixes I have to do in docs...

**Comment by ferrine** [comment]
@leuchine, @KhrulkovV going to finish this in 5hrs today. If you have any comments, this is the best time to write them.

**Comment by ferrine** [comment]
todos for today:

* #59 
* proofread the docs
* ... coming soon

**Comment by ferrine** [comment]
I faced numerical issues implementing #59, I have concerns about this change

**Comment by ferrine** [comment]
@newkozlukov please approve that you allow my merging this PR without changing the parametrization as you proposed in #59. And you will pick my work up on doing this some time. I approve this change (#59) and if done before 1.0.0 can go without backward compatible code. Once you approve this, I finish this PR and switch to others.

**Comment by ferrine** [comment]
Thank you all!

**Pull request merged**
