### PR TITLE
Birkhoff

### PR DESCRIPTION
**Pull request by ferrine**
Adding Birkhoff Polytope

CC @tolgabirdal

### CODE REVIEW

**Comment by ferrine** [comment]
@tolgabirdal, I found some numerical problems in the algorithm. Particularly, I see that vector projection is unstable

**Comment by tolgabirdal** [comment]
@ferrine With the current formulation, unstabilities are expected to arise as we approach the vertices of the polytope a.k.a. the permutation matrices. In the paper, to prevent that we implicitly use the frobenius norm as a regularizer. Is your test data close to the permutations?

Other than that for improving the numerical behavior of the sinkhorn one can do the typical log/exp trick. That we might incorporate in a future version.

**Comment by ferrine** [comment]
Actually, my test data is randomly generated. I do this to verify the correctness of implementation

**Comment by ferrine** [comment]
The current instability comes from tangent vector projection

**Comment by tolgabirdal** [comment]
In the original paper (eq. 25), this implementation is suggested as a more numerically stable way of doing the projection onto the tangent space. I am not sure how much it improves, but I am also not aware of a better way. Maybe we can increase the stability by some perturbation?
Additionally, I guess we should make sure that we use float64 for this manifold.

**Comment by ferrine** [comment]
I'll look at it. I'm always in favour on less restrictions for user. It affects speed and memory. It f32 does not drastically fail, then ok, if I have nans, there are problems

**Comment by ferrine** [comment]
hi, there is either a typo in the paper or I'm doing wroing with eq (25)

Following the paper I have to implement this

```python
def proj_tangent(x, u):
    assert x.shape[-2:] == u.shape[-2:], "Wrong shapes"
    x, u = torch.broadcast_tensors(x, u)
    shape = x.shape
    x = x.reshape(1, x.shape[-2], x.shape[-1])
    u = u.reshape(1, u.shape[-2], u.shape[-1])
    # u = x * u
    I = torch.eye(x.shape[-1], dtype=x.dtype, device=x.device)
    I = I.expand_as(x)
    xt = x.transpose(-1, -2)
    z1 = u.sum(dim=-1)
    zt1 = u.sum(dim=-2)
    X = block_matrix([
        [I, x],
        [xt, I]
    ])
    Z = torch.cat([z1, zt1], dim=-1)
    ab, _ = torch.solve(Z.unsqueeze(-1), X)
    ab = ab.squeeze(-1)
    a = ab.narrow(-1, 0, ab.size(-1) // 2)
    b = ab.narrow(-1, ab.size(-1) // 2, ab.size(-1) // 2)
    proj = u - (a.unsqueeze(-1) + b.unsqueeze(-2)) * x
    return proj.reshape(shape)
```

Testing this implementation in jupyter I noticed that it gives significantly different results from initially proposed in the PR (which I considered ok, but unstable)

The following commented fix `# u = x * u` seemed to help with it

However, tests we still not passing. Reading the paper briefly I noticed that the condition to check tangent vectors that was written in the PR may be wrong. What is said in the paper `u 1=0, u^t 1=0`, bun in the code I found the condition for stiefel manifold. I assumed it was a typo

**Comment by tolgabirdal** [comment]
@ferrine We have updated the tolga-develop branch and thus the pull request. Mostly, _check_vector_on_tangent and projx are updated. Though we could not reproduce the numerical instability you mentioned. Could you please check now and we can re-iterate accordingly.

**Comment by ferrine** [comment]
Hi, thanks, I'll find time to check that this week

пн, 3 февр. 2020 г., 3:21 Tolga Birdal <notifications@github.com>:

**Comment by ferrine** [comment]
I've checked it. Now we have similar implementations. I think it is ready to merge then

**Comment by ferrine** [comment]
@rrkarim to you have any review comments?

**Comment by rrkarim** [comment]
@ferrine sorry, the only concern I have is the assertion with absolute/relative error set to `1e-3`. But I guess it is discussed above in the thread and I'm approving it.

**Comment by ferrine** [comment]
Congrats, @tolgabirdal!

**Comment by tolgabirdal** [comment]
Thanks @ferrine and thanks to Haowen Deng (@denghw). Hoping to see geoopt evolve and happy to contribute further in the future.

**Pull request merged**
